spring.application.name=movie-info-service
server.port=8082

# MovieDB API Key
api.key=4ad2f55abb9a5482790d82d49743f689

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=movie_db