spring.application.name=movie-info-service
server.port=8082

# MovieDB API Key
api.key=e9b4507d335330bc8a077640c413acd4

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=movie_db