spring.application.name=trending-movies-service
server.port=8084
grpc.server.port=9090
spring.cache.type=caffeine
ratings.service.url=http://localhost:8083
movie.info.service.url=http://localhost:8082